# Generated by Django 3.2.4 on 2021-06-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleNumber', models.CharField(max_length=60)),
                ('vehicleStatus', models.CharField(max_length=60)),
                ('vehicleGroup', models.CharField(max_length=60)),
                ('totalPermits', models.CharField(max_length=60)),
                ('ownerPhone', models.CharField(max_length=60)),
                ('licenseStart', models.CharField(max_length=60)),
                ('licenseEnd', models.CharField(max_length=60)),
                ('licenseStatus', models.CharField(max_length=60)),
                ('capacity', models.CharField(max_length=60)),
                ('vehicleType', models.CharField(max_length=60)),
                ('gpsIMEI', models.CharField(max_length=60)),
                ('telecomProvider', models.CharField(max_length=60)),
                ('simNo', models.CharField(max_length=60)),
                ('registrationDate', models.CharField(max_length=60)),
                ('installationtype', models.CharField(max_length=60)),
                ('registrationBy', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
