# Generated by Django 3.2.4 on 2021-06-03 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210603_2330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicles',
            new_name='Trucks',
        ),
    ]
