# Generated by Django 3.2.4 on 2021-06-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_rename_vehicles_trucks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PermitNumber', models.CharField(max_length=60)),
                ('ILMS_number', models.CharField(max_length=60)),
                ('VehicleNumber', models.CharField(max_length=60)),
                ('PermitStart', models.CharField(max_length=60)),
                ('PermitValidTill', models.CharField(max_length=60)),
                ('LoadingLocation', models.CharField(max_length=60)),
                ('Destination', models.CharField(max_length=60)),
                ('Qty', models.CharField(max_length=60)),
                ('Alerts', models.CharField(max_length=60)),
            ],
        ),
    ]
