# Generated by Django 3.2.4 on 2021-06-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_permit'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=60)),
                ('PhoneNumber', models.CharField(max_length=60)),
            ],
        ),
    ]
