# Generated by Django 3.2.4 on 2021-06-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(default='123456', max_length=60),
        ),
    ]
