# Generated by Django 3.2.4 on 2021-06-07 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_auto_20210607_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterModelTable(
            name='permit',
            table='myapi_permit',
        ),
        migrations.AlterModelTable(
            name='trucks',
            table='myapi_trucks',
        ),
        migrations.AlterModelTable(
            name='user',
            table='myapi_user',
        ),
    ]
